import Link from "next/link";
import { Sparkles } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { EmptyState } from "@/components/shared/empty-state";
import { Card, CardContent } from "@/components/ui/card";
import { getDataRepository } from "@/services";
import { DEFAULT_LENDER_ID } from "@/lib/constants";
import { formatCurrency, formatDateTime } from "@/lib/utils";
import { recoveryActionLabels } from "@/lib/labels";

interface RecoveryPageProps {
  searchParams: Promise<{ status?: string }>;
}

export default async function RecoveryPage({ searchParams }: RecoveryPageProps) {
  const params = await searchParams;
  const repo = getDataRepository();
  const { data: recommendations, total } = await repo.getRecommendations(
    DEFAULT_LENDER_ID,
    { pageSize: 50, status: params.status }
  );

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Recovery Recommendations"
        description={`${total} recommendations generated by Amazon Nova`}
      />

      <div className="flex flex-wrap gap-2">
        {[
          { label: "All", value: undefined },
          { label: "Pending", value: "pending" },
          { label: "Approved", value: "approved" },
          { label: "Executed", value: "executed" },
          { label: "Rejected", value: "rejected" },
        ].map((filter) => {
          const isActive =
            params.status === filter.value ||
            (!params.status && !filter.value);
          return (
            <Link
              key={filter.label}
              href={
                filter.value ? `/recovery?status=${filter.value}` : "/recovery"
              }
              className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
                isActive
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-background hover:bg-muted"
              }`}
            >
              {filter.label}
            </Link>
          );
        })}
      </div>

      {recommendations.length === 0 ? (
        <EmptyState
          title="No recommendations found"
          description="AI recommendations will appear here when generated for overdue accounts."
          icon={<Sparkles className="h-10 w-10" />}
        />
      ) : (
        <div className="grid gap-4">
          {recommendations.map((rec) => (
            <Link key={rec.id} href={`/recovery/${rec.id}`}>
              <Card className="hover:bg-muted/30 transition-colors cursor-pointer">
                <CardContent className="p-6">
                  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                    <div className="space-y-2 min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <Sparkles className="h-4 w-4 text-primary shrink-0" />
                        <h3 className="font-semibold">{rec.title}</h3>
                        <StatusBadge status={rec.status} type="recommendation" />
                      </div>
                      <p className="text-sm text-muted-foreground line-clamp-2">
                        {rec.summary}
                      </p>
                      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
                        <span>
                          {rec.borrower.firstName} {rec.borrower.lastName}
                          {rec.borrower.company && ` · ${rec.borrower.company}`}
                        </span>
                        <span className="font-mono">{rec.loan.loanNumber}</span>
                        <span>{recoveryActionLabels[rec.action]}</span>
                      </div>
                    </div>
                    <div className="flex sm:flex-col items-start sm:items-end gap-2 shrink-0">
                      <div className="text-right">
                        <p className="text-lg font-bold text-primary">
                          {Math.round(rec.confidenceScore * 100)}%
                        </p>
                        <p className="text-xs text-muted-foreground">
                          confidence
                        </p>
                      </div>
                      {rec.expectedRecoveryAmount && (
                        <p className="text-sm">
                          Est. recovery:{" "}
                          <span className="font-medium">
                            {formatCurrency(rec.expectedRecoveryAmount)}
                          </span>
                        </p>
                      )}
                      <p className="text-xs text-muted-foreground">
                        {formatDateTime(rec.generatedAt)}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
