import { NextResponse } from "next/server";

const BASE_BORROWERS = [
  {
    id: "bor_001",
    firstName: "Robert",
    lastName: "Kim",
    company: "Pacific Builders Inc.",
    email: "r.kim@pacificbuilders.com",
    phone: "+1 (415) 882-3301",
    city: "San Francisco",
    state: "CA",
    creditScore: 548,
    riskLevel: "critical",
    totalLoans: 2,
    totalOutstanding: 1_100_000,
    onboardedAt: "2022-03-14T00:00:00Z",
  },
  {
    id: "bor_002",
    firstName: "Wei",
    lastName: "Chen",
    company: "Apex Logistics Group",
    email: "w.chen@apexlogistics.com",
    phone: "+1 (312) 554-9900",
    city: "Chicago",
    state: "IL",
    creditScore: 602,
    riskLevel: "high",
    totalLoans: 2,
    totalOutstanding: 485_000,
    onboardedAt: "2023-01-20T00:00:00Z",
  },
  {
    id: "bor_003",
    firstName: "Marcus",
    lastName: "Webb",
    company: "NovaBio Health Sciences",
    email: "m.webb@novabio.com",
    phone: "+1 (617) 449-1122",
    city: "Boston",
    state: "MA",
    creditScore: 631,
    riskLevel: "high",
    totalLoans: 1,
    totalOutstanding: 420_000,
    onboardedAt: "2023-02-10T00:00:00Z",
  },
  {
    id: "bor_004",
    firstName: "Sarah",
    lastName: "Whitfield",
    company: "Steel & Sons Mfg.",
    email: "s.whitfield@steelsons.com",
    phone: "+1 (216) 734-8820",
    city: "Cleveland",
    state: "OH",
    creditScore: 688,
    riskLevel: "medium",
    totalLoans: 1,
    totalOutstanding: 250_000,
    onboardedAt: "2023-07-05T00:00:00Z",
  },
  {
    id: "bor_005",
    firstName: "Alex",
    lastName: "Torres",
    company: "TechVault Solutions",
    email: "a.torres@techvault.io",
    phone: "+1 (512) 203-4477",
    city: "Austin",
    state: "TX",
    creditScore: 712,
    riskLevel: "medium",
    totalLoans: 1,
    totalOutstanding: 175_000,
    onboardedAt: "2023-09-11T00:00:00Z",
  },
  {
    id: "bor_006",
    firstName: "Priya",
    lastName: "Nair",
    company: "GreenLeaf Capital",
    email: "p.nair@greenleaf.com",
    phone: "+1 (646) 880-5533",
    city: "New York",
    state: "NY",
    creditScore: 754,
    riskLevel: "low",
    totalLoans: 1,
    totalOutstanding: 90_000,
    onboardedAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "bor_007",
    firstName: "James",
    lastName: "Okafor",
    company: "Okafor Retail Group",
    email: "j.okafor@okaforretail.com",
    phone: "+1 (404) 321-6654",
    city: "Atlanta",
    state: "GA",
    creditScore: 588,
    riskLevel: "high",
    totalLoans: 1,
    totalOutstanding: 310_000,
    onboardedAt: "2023-05-22T00:00:00Z",
  },
  {
    id: "bor_008",
    firstName: "Elena",
    lastName: "Vasquez",
    company: "Sunrise Hospitality LLC",
    email: "e.vasquez@sunrisehospitality.com",
    phone: "+1 (305) 744-2211",
    city: "Miami",
    state: "FL",
    creditScore: 671,
    riskLevel: "medium",
    totalLoans: 1,
    totalOutstanding: 140_000,
    onboardedAt: "2024-03-15T00:00:00Z",
  },
];

export async function GET() {
  const borrowers = BASE_BORROWERS.map((b) => ({
    ...b,
    creditScore: b.creditScore + Math.floor(Math.random() * 7) - 3,
    totalOutstanding: b.totalOutstanding + Math.floor(Math.random() * 10_000) - 5_000,
  }));

  return NextResponse.json({
    borrowers,
    total: borrowers.length,
    highRisk: borrowers.filter((b) => b.riskLevel === "high" || b.riskLevel === "critical").length,
    totalExposure: borrowers.reduce((s, b) => s + b.totalOutstanding, 0),
    updatedAt: new Date().toISOString(),
  });
}
